/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "d_b_request.h"

gboolean
d_b_request_if_ping (DBRequestIf *iface, GError **error)
{
  return D_B_REQUEST_IF_GET_INTERFACE (iface)->ping (iface, error);
}

gboolean
d_b_request_if_do_request (DBRequestIf *iface, Answer_TRANSPORT ** _return, const Request_TRANSPORT * req, GError **error)
{
  return D_B_REQUEST_IF_GET_INTERFACE (iface)->do_request (iface, _return, req, error);
}

GType
d_b_request_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (DBRequestIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "DBRequestIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
d_b_request_if_interface_init (DBRequestIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (DBRequestClient, d_b_request_client,
                         G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (TYPE_D_B_REQUEST_IF,
                                                d_b_request_if_interface_init))

enum _DBRequestClientProperties
{
  PROP_0,
  PROP_D_B_REQUEST_CLIENT_INPUT_PROTOCOL,
  PROP_D_B_REQUEST_CLIENT_OUTPUT_PROTOCOL
};

void
d_b_request_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  DBRequestClient *client = D_B_REQUEST_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_D_B_REQUEST_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_D_B_REQUEST_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
d_b_request_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  DBRequestClient *client = D_B_REQUEST_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_D_B_REQUEST_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_D_B_REQUEST_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

gboolean d_b_request_client_send_ping (DBRequestIf * iface, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = D_B_REQUEST_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "ping", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "ping_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean d_b_request_client_recv_ping (DBRequestIf * iface, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = D_B_REQUEST_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "ping", 4) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected ping", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean d_b_request_client_ping (DBRequestIf * iface, GError ** error)
{
  if (!d_b_request_client_send_ping (iface, error))
    return FALSE;
  if (!d_b_request_client_recv_ping (iface, error))
    return FALSE;
  return TRUE;
}

gboolean d_b_request_client_send_do_request (DBRequestIf * iface, const Request_TRANSPORT * req, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = D_B_REQUEST_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "do_request", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "do_request_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "req", T_STRUCT, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (req), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean d_b_request_client_recv_do_request (DBRequestIf * iface, Answer_TRANSPORT ** _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = D_B_REQUEST_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "do_request", 10) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected do_request", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRUCT)
          {
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*_return), protocol, error)) < 0)
            {
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean d_b_request_client_do_request (DBRequestIf * iface, Answer_TRANSPORT ** _return, const Request_TRANSPORT * req, GError ** error)
{
  if (!d_b_request_client_send_do_request (iface, req, error))
    return FALSE;
  if (!d_b_request_client_recv_do_request (iface, _return, error))
    return FALSE;
  return TRUE;
}

static void
d_b_request_if_interface_init (DBRequestIfInterface *iface)
{
  iface->ping = d_b_request_client_ping;
  iface->do_request = d_b_request_client_do_request;
}

static void
d_b_request_client_init (DBRequestClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
d_b_request_client_class_init (DBRequestClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = d_b_request_client_set_property;
  gobject_class->get_property = d_b_request_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_D_B_REQUEST_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_D_B_REQUEST_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

static void
d_b_request_handler_d_b_request_if_interface_init (DBRequestIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (DBRequestHandler, 
                         d_b_request_handler,
                         G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (TYPE_D_B_REQUEST_IF,
                                                d_b_request_handler_d_b_request_if_interface_init))

gboolean d_b_request_handler_ping (DBRequestIf * iface, GError ** error)
{
  g_return_val_if_fail (IS_D_B_REQUEST_HANDLER (iface), FALSE);

  return D_B_REQUEST_HANDLER_GET_CLASS (iface)->ping (iface, error);
}

gboolean d_b_request_handler_do_request (DBRequestIf * iface, Answer_TRANSPORT ** _return, const Request_TRANSPORT * req, GError ** error)
{
  g_return_val_if_fail (IS_D_B_REQUEST_HANDLER (iface), FALSE);

  return D_B_REQUEST_HANDLER_GET_CLASS (iface)->do_request (iface, _return, req, error);
}

static void
d_b_request_handler_d_b_request_if_interface_init (DBRequestIfInterface *iface)
{
  iface->ping = d_b_request_handler_ping;
  iface->do_request = d_b_request_handler_do_request;
}

static void
d_b_request_handler_init (DBRequestHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
d_b_request_handler_class_init (DBRequestHandlerClass *cls)
{
  cls->ping = NULL;
  cls->do_request = NULL;
}

enum _DBRequestProcessorProperties
{
  PROP_D_B_REQUEST_PROCESSOR_0,
  PROP_D_B_REQUEST_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (DBRequestProcessor,
               d_b_request_processor,
               THRIFT_TYPE_DISPATCH_PROCESSOR)

typedef gboolean (* DBRequestProcessorProcessFunction) (DBRequestProcessor *, 
                                                        gint32,
                                                        ThriftProtocol *,
                                                        ThriftProtocol *,
                                                        GError **);

typedef struct
{
  gchar *name;
  DBRequestProcessorProcessFunction function;
} d_b_request_processor_process_function_def;

static gboolean
d_b_request_processor_process_ping (DBRequestProcessor *,
                                    gint32,
                                    ThriftProtocol *,
                                    ThriftProtocol *,
                                    GError **);
static gboolean
d_b_request_processor_process_do_request (DBRequestProcessor *,
                                          gint32,
                                          ThriftProtocol *,
                                          ThriftProtocol *,
                                          GError **);

static d_b_request_processor_process_function_def
d_b_request_processor_process_function_defs[2] = {
  {
    "ping",
    d_b_request_processor_process_ping
  },
  {
    "do_request",
    d_b_request_processor_process_do_request
  }
};

static gboolean
d_b_request_processor_process_ping (DBRequestProcessor *self,
                                    gint32 sequence_id,
                                    ThriftProtocol *input_protocol,
                                    ThriftProtocol *output_protocol,
                                    GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  DBRequestPingArgs * args =
    g_object_new (TYPE_D_B_REQUEST_PING_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    DBRequestPingResult * result_struct;

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_D_B_REQUEST_PING_RESULT, NULL);

    if (d_b_request_handler_ping (D_B_REQUEST_IF (self->handler),
                                  error) == TRUE)
    {
      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "ping",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("DBRequest.ping implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "ping",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
d_b_request_processor_process_do_request (DBRequestProcessor *self,
                                          gint32 sequence_id,
                                          ThriftProtocol *input_protocol,
                                          ThriftProtocol *output_protocol,
                                          GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  DBRequestDoRequestArgs * args =
    g_object_new (TYPE_D_B_REQUEST_DO_REQUEST_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    Request_TRANSPORT * req;
    Answer_TRANSPORT * return_value;
    DBRequestDoRequestResult * result_struct;

    g_object_get (args,
                  "req", &req,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_D_B_REQUEST_DO_REQUEST_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (d_b_request_handler_do_request (D_B_REQUEST_IF (self->handler),
                                        &return_value,
                                        req,
                                        error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "do_request",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("DBRequest.do_request implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "do_request",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (req != NULL)
      g_object_unref (req);
    if (return_value != NULL)
      g_object_unref (return_value);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
d_b_request_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                     ThriftProtocol *input_protocol,
                                     ThriftProtocol *output_protocol,
                                     gchar *method_name,
                                     gint32 sequence_id,
                                     GError **error)
{
  d_b_request_processor_process_function_def *process_function_def;
  gboolean dispatch_result = FALSE;

  DBRequestProcessor *self = D_B_REQUEST_PROCESSOR (dispatch_processor);
  ThriftDispatchProcessorClass *parent_class =
    g_type_class_peek_parent (D_B_REQUEST_PROCESSOR_GET_CLASS (self));

  process_function_def = g_hash_table_lookup (self->process_map, method_name);
  if (process_function_def != NULL)
  {
    g_free (method_name);
    dispatch_result = (*process_function_def->function) (self,
                                                         sequence_id,
                                                         input_protocol,
                                                         output_protocol,
                                                         error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
d_b_request_processor_set_property (GObject *object,
                                    guint property_id,
                                    const GValue *value,
                                    GParamSpec *pspec)
{
  DBRequestProcessor *self = D_B_REQUEST_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_D_B_REQUEST_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
d_b_request_processor_get_property (GObject *object,
                                    guint property_id,
                                    GValue *value,
                                    GParamSpec *pspec)
{
  DBRequestProcessor *self = D_B_REQUEST_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_D_B_REQUEST_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
d_b_request_processor_dispose (GObject *gobject)
{
  DBRequestProcessor *self = D_B_REQUEST_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (d_b_request_processor_parent_class)->dispose (gobject);
}

static void
d_b_request_processor_finalize (GObject *gobject)
{
  DBRequestProcessor *self = D_B_REQUEST_PROCESSOR (gobject);

  thrift_safe_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (d_b_request_processor_parent_class)->finalize (gobject);
}

static void
d_b_request_processor_init (DBRequestProcessor *self)
{
  guint index;

  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);

  for (index = 0; index < 2; index += 1)
    g_hash_table_insert (self->process_map,
                         d_b_request_processor_process_function_defs[index].name,
                         &d_b_request_processor_process_function_defs[index]);
}

static void
d_b_request_processor_class_init (DBRequestProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = d_b_request_processor_dispose;
  gobject_class->finalize = d_b_request_processor_finalize;
  gobject_class->set_property = d_b_request_processor_set_property;
  gobject_class->get_property = d_b_request_processor_get_property;

  dispatch_processor_class->dispatch_call = d_b_request_processor_dispatch_call;
  cls->dispatch_call = d_b_request_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    TYPE_D_B_REQUEST_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_D_B_REQUEST_PROCESSOR_HANDLER,
                                   param_spec);
}
